name: Build and Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: dotnet restore .\SchemaExporter.slnx

      - name: Build
        run: dotnet build .\SchemaExporter.slnx -c Release --no-restore

      - name: Test
        run: dotnet test .\SchemaExporter.slnx -c Release --no-build --verbosity minimal

      - name: Publish app
        run: dotnet publish .\src\SchemaExporter\SchemaExporter.csproj -c Release --self-contained -r win-x64 -o .\artifacts\publish

      - name: Pack Velopack
        uses: CloudyWing/devops-templates/.github/actions/velopack-pack@main
        with:
          version: ${{ github.ref_name }}
          pack-id: CloudyWing.SchemaExporter
          main-exe: CloudyWing.SchemaExporter.exe
          pack-dir: .\artifacts\publish
          output-dir: .\artifacts\velopack

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: velopack
          path: artifacts/velopack/*

  create-release:
    needs: build
    uses: CloudyWing/devops-templates/.github/workflows/reusable-create-release.yml@main

  upload-release-assets:
    needs: create-release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: velopack
          path: artifacts/velopack

      - name: Upload release assets
        run: gh release upload ${{ github.ref_name }} artifacts/velopack/*
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
